# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Full Pipline

on:
  push:
    branches:
      - main

jobs:
  full-pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:

      - uses: actions/checkout@v3
#scan
      - name: Scan source code
        uses: anchore/scan-action@v3
        with:
          path: "${{ github.workspace }}"
          fail-build: false
#build
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
#test
      - name: Run Maven Tests
        run: mvn test --file pom.xml
#docker
      - name: Build Docker Image
        run: docker build -t bengold7/project-green:latest .
#security
      - name: Scan Docker Image
        uses: anchore/scan-action@v3
        with:
          image: "bengold7/project-green:latest"
          fail-build: false
          output-format: json
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: AnchoreReports
          path: ./anchore-reports/
      - name: Create SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
      - name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: false
